import { PrismaService } from '../prisma.service';
import { UpdateUserInput } from '../auth/dto/update-user.input';
import { EventsGateway } from '../events/events.gateway';
import { User as PrismaUser } from '@prisma/client';
import { UsersService } from './users.service';
import { UpdateNotificationSettingsInput } from './dto/update-notification-settings.input';
import { NotificationSettingsModel } from './models/notification-settings.model';
export declare class UsersResolver {
    private prisma;
    private eventsGateway;
    private usersService;
    constructor(prisma: PrismaService, eventsGateway: EventsGateway, usersService: UsersService);
    private checkIsBlocked;
    blockUser(context: any, targetId: number): Promise<boolean>;
    unblockUser(context: any, targetId: number): Promise<boolean>;
    deleteMyAccount(password: string, context: any): Promise<boolean>;
    vibes(user: PrismaUser, context: any): Promise<{
        isLikedByUser: boolean;
        author: {
            id: number;
            email: string;
            username: string;
            name: string;
            password: string;
            isOnline: boolean;
            lastOnlineAt: Date;
            isAdmin: boolean;
            isVerified: boolean;
            createdAt: Date;
            bio: string;
            location: string;
            gender: string;
            website: string;
            avatar: string;
            banner: string;
        };
        id: number;
        createdAt: Date;
        likesCount: number;
        repostsCount: number;
        commentsCount: number;
        authorId: number;
        description: string | null;
        viewsCount: number;
        videoUrl: string;
        hashtags: string[];
        isPrivate: boolean;
    }[]>;
    posts(user: PrismaUser, context: any): Promise<{
        isLikedByUser: boolean;
        author: {
            id: number;
            email: string;
            username: string;
            name: string;
            password: string;
            isOnline: boolean;
            lastOnlineAt: Date;
            isAdmin: boolean;
            isVerified: boolean;
            createdAt: Date;
            bio: string;
            location: string;
            gender: string;
            website: string;
            avatar: string;
            banner: string;
        };
        vibe: {
            author: {
                id: number;
                email: string;
                username: string;
                name: string;
                password: string;
                isOnline: boolean;
                lastOnlineAt: Date;
                isAdmin: boolean;
                isVerified: boolean;
                createdAt: Date;
                bio: string;
                location: string;
                gender: string;
                website: string;
                avatar: string;
                banner: string;
            };
        } & {
            id: number;
            createdAt: Date;
            likesCount: number;
            repostsCount: number;
            commentsCount: number;
            authorId: number;
            description: string | null;
            viewsCount: number;
            videoUrl: string;
            hashtags: string[];
            isPrivate: boolean;
        };
        originalPost: {
            author: {
                id: number;
                email: string;
                username: string;
                name: string;
                password: string;
                isOnline: boolean;
                lastOnlineAt: Date;
                isAdmin: boolean;
                isVerified: boolean;
                createdAt: Date;
                bio: string;
                location: string;
                gender: string;
                website: string;
                avatar: string;
                banner: string;
            };
            vibe: {
                author: {
                    id: number;
                    email: string;
                    username: string;
                    name: string;
                    password: string;
                    isOnline: boolean;
                    lastOnlineAt: Date;
                    isAdmin: boolean;
                    isVerified: boolean;
                    createdAt: Date;
                    bio: string;
                    location: string;
                    gender: string;
                    website: string;
                    avatar: string;
                    banner: string;
                };
            } & {
                id: number;
                createdAt: Date;
                likesCount: number;
                repostsCount: number;
                commentsCount: number;
                authorId: number;
                description: string | null;
                viewsCount: number;
                videoUrl: string;
                hashtags: string[];
                isPrivate: boolean;
            };
        } & {
            id: number;
            createdAt: Date;
            updatedAt: Date;
            content: string | null;
            images: string[];
            commentsDisabled: boolean;
            isPinned: boolean;
            isPublished: boolean;
            scheduledAt: Date | null;
            likesCount: number;
            repostsCount: number;
            commentsCount: number;
            authorId: number;
            vibeId: number | null;
            originalPostId: number | null;
            repostedById: number | null;
        };
        id: number;
        createdAt: Date;
        updatedAt: Date;
        content: string | null;
        images: string[];
        commentsDisabled: boolean;
        isPinned: boolean;
        isPublished: boolean;
        scheduledAt: Date | null;
        likesCount: number;
        repostsCount: number;
        commentsCount: number;
        authorId: number;
        vibeId: number | null;
        originalPostId: number | null;
        repostedById: number | null;
    }[]>;
    likedPosts(user: PrismaUser, context: any): Promise<{
        isLikedByUser: boolean;
        author: {
            id: number;
            email: string;
            username: string;
            name: string;
            password: string;
            isOnline: boolean;
            lastOnlineAt: Date;
            isAdmin: boolean;
            isVerified: boolean;
            createdAt: Date;
            bio: string;
            location: string;
            gender: string;
            website: string;
            avatar: string;
            banner: string;
        };
        vibe: {
            author: {
                id: number;
                email: string;
                username: string;
                name: string;
                password: string;
                isOnline: boolean;
                lastOnlineAt: Date;
                isAdmin: boolean;
                isVerified: boolean;
                createdAt: Date;
                bio: string;
                location: string;
                gender: string;
                website: string;
                avatar: string;
                banner: string;
            };
        } & {
            id: number;
            createdAt: Date;
            likesCount: number;
            repostsCount: number;
            commentsCount: number;
            authorId: number;
            description: string | null;
            viewsCount: number;
            videoUrl: string;
            hashtags: string[];
            isPrivate: boolean;
        };
        originalPost: {
            author: {
                id: number;
                email: string;
                username: string;
                name: string;
                password: string;
                isOnline: boolean;
                lastOnlineAt: Date;
                isAdmin: boolean;
                isVerified: boolean;
                createdAt: Date;
                bio: string;
                location: string;
                gender: string;
                website: string;
                avatar: string;
                banner: string;
            };
            vibe: {
                author: {
                    id: number;
                    email: string;
                    username: string;
                    name: string;
                    password: string;
                    isOnline: boolean;
                    lastOnlineAt: Date;
                    isAdmin: boolean;
                    isVerified: boolean;
                    createdAt: Date;
                    bio: string;
                    location: string;
                    gender: string;
                    website: string;
                    avatar: string;
                    banner: string;
                };
            } & {
                id: number;
                createdAt: Date;
                likesCount: number;
                repostsCount: number;
                commentsCount: number;
                authorId: number;
                description: string | null;
                viewsCount: number;
                videoUrl: string;
                hashtags: string[];
                isPrivate: boolean;
            };
        } & {
            id: number;
            createdAt: Date;
            updatedAt: Date;
            content: string | null;
            images: string[];
            commentsDisabled: boolean;
            isPinned: boolean;
            isPublished: boolean;
            scheduledAt: Date | null;
            likesCount: number;
            repostsCount: number;
            commentsCount: number;
            authorId: number;
            vibeId: number | null;
            originalPostId: number | null;
            repostedById: number | null;
        };
        poll: {
            votes: {
                userId: number;
                pollId: number;
                pollOptionId: number;
            }[];
            options: {
                id: number;
                text: string;
                pollId: number;
            }[];
        } & {
            id: number;
            createdAt: Date;
            updatedAt: Date;
            postId: number;
            isAnonymous: boolean;
            question: string;
            endDate: Date;
            allowMultipleVotes: boolean;
            allowRevote: boolean;
        };
        id: number;
        createdAt: Date;
        updatedAt: Date;
        content: string | null;
        images: string[];
        commentsDisabled: boolean;
        isPinned: boolean;
        isPublished: boolean;
        scheduledAt: Date | null;
        likesCount: number;
        repostsCount: number;
        commentsCount: number;
        authorId: number;
        vibeId: number | null;
        originalPostId: number | null;
        repostedById: number | null;
    }[]>;
    likedVibes(user: PrismaUser, context: any): Promise<{
        isLikedByUser: boolean;
        author: {
            id: number;
            email: string;
            username: string;
            name: string;
            password: string;
            isOnline: boolean;
            lastOnlineAt: Date;
            isAdmin: boolean;
            isVerified: boolean;
            createdAt: Date;
            bio: string;
            location: string;
            gender: string;
            website: string;
            avatar: string;
            banner: string;
        };
        id: number;
        createdAt: Date;
        likesCount: number;
        repostsCount: number;
        commentsCount: number;
        authorId: number;
        description: string | null;
        viewsCount: number;
        videoUrl: string;
        hashtags: string[];
        isPrivate: boolean;
    }[]>;
    likedComments(user: PrismaUser, context: any): Promise<{
        userVote: "LIKE" | "DISLIKE";
        likesCount: number;
        dislikesCount: number;
        score: number;
        author: {
            id: number;
            email: string;
            username: string;
            name: string;
            password: string;
            isOnline: boolean;
            lastOnlineAt: Date;
            isAdmin: boolean;
            isVerified: boolean;
            createdAt: Date;
            bio: string;
            location: string;
            gender: string;
            website: string;
            avatar: string;
            banner: string;
        };
        post: {
            id: number;
            content: string;
            images: string[];
        };
        id: number;
        createdAt: Date;
        updatedAt: Date;
        content: string;
        authorId: number;
        postId: number;
        parentId: number | null;
    }[]>;
    me(context: any): Promise<{
        id: number;
        email: string;
        username: string;
        name: string;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string;
        location: string;
        gender: string;
        website: string;
        avatar: string;
        banner: string;
    }>;
    user(id: number): Promise<{
        id: number;
        email: string;
        username: string;
        name: string;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string;
        location: string;
        gender: string;
        website: string;
        avatar: string;
        banner: string;
    }>;
    terminateSession(sessionId: number, password: string, context: any): Promise<boolean>;
    terminateAllOtherSessions(password: string, context: any): Promise<boolean>;
    mySessions(context: any): Promise<{
        isCurrent: boolean;
        id: number;
        createdAt: Date;
        updatedAt: Date;
        userId: number;
        token: string;
        userAgent: string | null;
        ip: string | null;
        device: string | null;
        os: string | null;
        browser: string | null;
        city: string | null;
        country: string | null;
        lastActive: Date;
        expiresAt: Date | null;
    }[]>;
    myNotificationSettings(context: any): Promise<NotificationSettingsModel>;
    updateNotificationSettings(context: any, input: UpdateNotificationSettingsInput): Promise<boolean>;
    checkUsername(username: string): Promise<boolean>;
    updateProfile(context: any, input: UpdateUserInput): Promise<{
        id: number;
        email: string;
        username: string;
        name: string;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string;
        location: string;
        gender: string;
        website: string;
        avatar: string;
        banner: string;
    }>;
    postsCount(user: PrismaUser): Promise<number>;
    friendsCount(user: PrismaUser): Promise<number>;
    subscriptionsCount(user: PrismaUser): Promise<number>;
    followersCount(user: PrismaUser): Promise<number>;
    friends(user: PrismaUser, context: any): Promise<{
        id: number;
        email: string;
        username: string;
        name: string;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string;
        location: string;
        gender: string;
        website: string;
        avatar: string;
        banner: string;
    }[]>;
    subscriptions(user: PrismaUser, context: any): Promise<{
        id: number;
        email: string;
        username: string;
        name: string | null;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date | null;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string | null;
        location: string | null;
        gender: string | null;
        website: string | null;
        avatar: string | null;
        banner: string | null;
    }[]>;
    followers(user: PrismaUser, context: any): Promise<{
        id: number;
        email: string;
        username: string;
        name: string | null;
        password: string;
        isOnline: boolean;
        lastOnlineAt: Date | null;
        isAdmin: boolean;
        isVerified: boolean;
        createdAt: Date;
        bio: string | null;
        location: string | null;
        gender: string | null;
        website: string | null;
        avatar: string | null;
        banner: string | null;
    }[]>;
    friendshipStatus(profileUser: PrismaUser, context: any): Promise<"NONE" | "FRIEND" | "REQUEST_SENT" | "REQUEST_RECEIVED">;
    sentFriendRequestId(profileUser: PrismaUser, context: any): Promise<number>;
    receivedFriendRequestId(profileUser: PrismaUser, context: any): Promise<number>;
    avatar(user: PrismaUser, context: any): Promise<string>;
    isOnline(user: PrismaUser, context: any): Promise<boolean>;
    lastOnlineAt(user: PrismaUser, context: any): Promise<Date>;
    amIBlocked(user: PrismaUser, context: any): Promise<boolean>;
    isBlockedByMe(user: PrismaUser, context: any): Promise<boolean>;
}
